-- MySQL Script generated by MySQL Workbench
-- lun 28 jun 2021 22:24:55 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pi_temperatures
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pi_temperatures` ;

-- -----------------------------------------------------
-- Schema pi_temperatures
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi_temperatures` ;
USE `pi_temperatures` ;

-- -----------------------------------------------------
-- Table `pi_temperatures`.`temperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_temperatures`.`temperature` ;

CREATE TABLE IF NOT EXISTS `pi_temperatures`.`temperature` (
  `idtemperature` INT NOT NULL AUTO_INCREMENT,
  `temperature_celsius` FLOAT NOT NULL,
  PRIMARY KEY (`idtemperature`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_temperatures`.`temp_listing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_temperatures`.`temp_listing` ;

CREATE TABLE IF NOT EXISTS `pi_temperatures`.`temp_listing` (
  `idtemp_listing` INT NOT NULL AUTO_INCREMENT,
  `date_of_change` DATETIME NOT NULL,
  `rise` TINYINT NOT NULL,
  `temperature_idtemperature` INT NOT NULL,
  PRIMARY KEY (`idtemp_listing`),
  INDEX `fk_temp_listing_temperature1_idx` (`temperature_idtemperature` ASC) VISIBLE,
  CONSTRAINT `fk_temp_listing_temperature1`
    FOREIGN KEY (`temperature_idtemperature`)
    REFERENCES `pi_temperatures`.`temperature` (`idtemperature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_temperatures`.`fan_use`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_temperatures`.`fan_use` ;

CREATE TABLE IF NOT EXISTS `pi_temperatures`.`fan_use` (
  `idfan_use` INT NOT NULL AUTO_INCREMENT,
  `datetime_on` DATETIME NOT NULL,
  `datetime_off` DATETIME NOT NULL,
  `temp_listing_idtemp_listing` INT NOT NULL,
  PRIMARY KEY (`idfan_use`),
  INDEX `fk_fan_use_temp_listing1_idx` (`temp_listing_idtemp_listing` ASC) VISIBLE,
  CONSTRAINT `fk_fan_use_temp_listing1`
    FOREIGN KEY (`temp_listing_idtemp_listing`)
    REFERENCES `pi_temperatures`.`temp_listing` (`idtemp_listing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_temperatures`.`fan_potency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_temperatures`.`fan_potency` ;

CREATE TABLE IF NOT EXISTS `pi_temperatures`.`fan_potency` (
  `idfan_potency` INT NOT NULL AUTO_INCREMENT,
  `potency` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfan_potency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_temperatures`.`fan_potency_use`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_temperatures`.`fan_potency_use` ;

CREATE TABLE IF NOT EXISTS `pi_temperatures`.`fan_potency_use` (
  `idfan_potency_use` INT NOT NULL AUTO_INCREMENT,
  `datetime_of_potency` DATETIME NOT NULL,
  `fan_potency_idfan_potency` INT NOT NULL,
  `idfan_potency_use` INT NOT NULL,
  INDEX `fk_fan_use_fan_use1_idx` (`idfan_potency_use` ASC) VISIBLE,
  PRIMARY KEY (`idfan_potency_use`),
  CONSTRAINT `fk_fan_use_fan_potency1`
    FOREIGN KEY (`fan_potency_idfan_potency`)
    REFERENCES `pi_temperatures`.`fan_potency` (`idfan_potency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fan_use_fan_use1`
    FOREIGN KEY (`idfan_potency_use`)
    REFERENCES `pi_temperatures`.`fan_use` (`idfan_use`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_temperatures`.`humidity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_temperatures`.`humidity` ;

CREATE TABLE IF NOT EXISTS `pi_temperatures`.`humidity` (
  `idhumidity_listing` INT NOT NULL AUTO_INCREMENT,
  `humidity` DECIMAL NOT NULL,
  PRIMARY KEY (`idhumidity_listing`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_temperatures`.`service_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_temperatures`.`service_data` ;

CREATE TABLE IF NOT EXISTS `pi_temperatures`.`service_data` (
  `idservice_data` INT NOT NULL AUTO_INCREMENT,
  `feels_like` DECIMAL NOT NULL,
  `temp_listing_idtemp_listing` INT NOT NULL,
  `temperature_idtemperature` INT NOT NULL,
  `humidity_idhumidity_listing` INT NOT NULL,
  PRIMARY KEY (`idservice_data`),
  INDEX `fk_service_data_temp_listing1_idx` (`temp_listing_idtemp_listing` ASC) VISIBLE,
  INDEX `fk_service_data_temperature1_idx` (`temperature_idtemperature` ASC) VISIBLE,
  INDEX `fk_service_data_humidity1_idx` (`humidity_idhumidity_listing` ASC) VISIBLE,
  CONSTRAINT `fk_service_data_temp_listing1`
    FOREIGN KEY (`temp_listing_idtemp_listing`)
    REFERENCES `pi_temperatures`.`temp_listing` (`idtemp_listing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_data_temperature1`
    FOREIGN KEY (`temperature_idtemperature`)
    REFERENCES `pi_temperatures`.`temperature` (`idtemperature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_data_humidity1`
    FOREIGN KEY (`humidity_idhumidity_listing`)
    REFERENCES `pi_temperatures`.`humidity` (`idhumidity_listing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi_temperatures`.`humidity_in_temp_listing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pi_temperatures`.`humidity_in_temp_listing` ;

CREATE TABLE IF NOT EXISTS `pi_temperatures`.`humidity_in_temp_listing` (
  `idhumidity_in_temp_listing` INT NOT NULL AUTO_INCREMENT,
  `registered_datetime` DATETIME NOT NULL,
  `humidity_idhumidity_listing` INT NOT NULL,
  `temp_listing_idtemp_listing` INT NOT NULL,
  `temp_listing_temperature_idtemperature` INT NOT NULL,
  PRIMARY KEY (`idhumidity_in_temp_listing`),
  INDEX `fk_humidity_in_temp_listing_humidity1_idx` (`humidity_idhumidity_listing` ASC) VISIBLE,
  INDEX `fk_humidity_in_temp_listing_temp_listing1_idx` (`temp_listing_idtemp_listing` ASC, `temp_listing_temperature_idtemperature` ASC) VISIBLE,
  CONSTRAINT `fk_humidity_in_temp_listing_humidity1`
    FOREIGN KEY (`humidity_idhumidity_listing`)
    REFERENCES `pi_temperatures`.`humidity` (`idhumidity_listing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_humidity_in_temp_listing_temp_listing1`
    FOREIGN KEY (`temp_listing_idtemp_listing` , `temp_listing_temperature_idtemperature`)
    REFERENCES `pi_temperatures`.`temp_listing` (`idtemp_listing` , `temperature_idtemperature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
